1:
	g++ -o game Application.cpp -lSDL2 -lSDL2_mixer -lSDL2_ttf -lSDL2_image && ./game
2: 
	g++ -o main main.cpp -lSDL2 -lSDL2_mixer -lSDL2_ttf -lSDL2_image && ./game
3: 	
	g++ -o 1game 1Application.cpp -lSDL2 -lSDL2_mixer -lSDL2_ttf -lSDL2_image && ./1game
